/*
 * Bike.ts — Mongoose model for motorcycle listings.
 *
 * MPD Task DB-02:
 *   "Mongoose model for Bike. Full schema covering all spec fields,
 *   gallery, colors, pricing, SEO fields, publish status.
 *   Indexes on brandSlug, category, status, slug (unique)."
 *
 * MPD Section 8, Technical Architecture — Data Models:
 *   "Bike document: slug, brandSlug, name, tagline, category, status,
 *   pricing (exShowroom, onRoad), specs (engine, dimensions, features),
 *   colors (name, hex, imageUrl), gallery (images, video360Url),
 *   seo (metaTitle, metaDescription, canonicalUrl),
 *   publishedAt, createdAt, updatedAt."
 *
 * MPD Section 5.3, Bike Detail Page fields:
 *   Engine specs: displacement, type, maxPower, maxTorque,
 *   fuelSystem, coolingType.
 *   Dimensions: kerbWeight, fuelCapacity, seatHeight,
 *   groundClearance, wheelbase.
 *   Features: ABS, traction control, riding modes, Bluetooth,
 *   USB charging, quickshifter.
 *   Gallery: up to 10 images + optional 360-degree video.
 *   Colors: name, hex swatch, per-color hero image from Cloudinary.
 *
 * SINGLETON PATTERN:
 *   Next.js hot-reload re-executes module code, which would call
 *   mongoose.model() multiple times and throw:
 *   "Cannot overwrite `Bike` model once compiled."
 *   The `mongoose.models.Bike || mongoose.model(...)` pattern
 *   returns the existing model if already registered, only creating
 *   a new model on the first call.
 *
 * TYPE STRATEGY:
 *   Each sub-document schema has a corresponding TypeScript interface.
 *   The top-level IBike interface extends mongoose.Document so that
 *   model methods (.save(), .toObject()) are fully typed.
 *   IBikeInput is a plain-object version (without Document methods)
 *   used by API route handlers for creating/updating bikes.
 *
 * CLOUDINARY URLS:
 *   All image URLs are Cloudinary delivery URLs.
 *   They are stored as strings (not Cloudinary public_ids) so that
 *   the frontend can use them directly with Next.js Image.
 *   Format: https://res.cloudinary.com/[cloud]/image/upload/[transforms]/[public_id]
 *
 * INDEXES:
 *   slug:      unique — enforces one document per URL slug
 *   brandSlug: compound with status — listing pages query by brand+status
 *   category:  compound with status — category pages query by category+status
 *   status:    standalone — admin queries all drafts or all published
 *   publishedAt: descending — "recently published" sort on listing pages
 *
 * SLUG GENERATION:
 *   Slugs are set by the admin when creating a bike.
 *   Format: [brand-slug]-[model-name-kebab] e.g. "royal-enfield-gt-650"
 *   The unique index enforces no duplicates at the database level.
 *   Slug validation regex: /^[a-z0-9]+(?:-[a-z0-9]+)*$/
 */

import mongoose, {
    type Document,
    type Model,
    Schema,
  } from 'mongoose'
  
  // ---------------------------------------------------------------------------
  // Sub-document interfaces
  // ---------------------------------------------------------------------------
  
  /*
   * IBikeColor — a single available color variant for a motorcycle.
   * Bikes can have 1–8 color options.
   */
  export interface IBikeColor {
    /*
     * name — display name of the color variant.
     * Example: "Celestial Blue", "Signals Green"
     */
    name: string
  
    /*
     * hex — CSS hex code for the color swatch.
     * Displayed in the color selector on the bike detail page (B-05).
     * Example: "#1B3A8A", "#4A7C59"
     */
    hex: string
  
    /*
     * imageUrl — Cloudinary URL of the hero image for this color.
     * Different from the primary heroImageUrl (which shows the default color).
     * Allows the color selector to update the hero image on selection.
     * Optional: falls back to heroImageUrl if not provided.
     */
    imageUrl?: string
  }
  
  /*
   * IBikeGalleryImage — a single image in the bike's photo gallery.
   */
  export interface IBikeGalleryImage {
    /*
     * url — Cloudinary delivery URL for this gallery image.
     * Next.js Image requires the domain to be in next.config.ts remotePatterns.
     */
    url: string
  
    /*
     * alt — accessible alt text for this image.
     * Required for accessibility (WCAG 2.1 AA).
     * Example: "Royal Enfield GT 650 side profile in Ventura Blue"
     */
    alt: string
  
    /*
     * blurDataUrl — base64 encoded 20×20px placeholder for blur-up loading.
     * Generated by Cloudinary (e_blur:1000,w_20,h_20,f_webp) and stored
     * at upload time. Optional — falls back to empty placeholder if absent.
     */
    blurDataUrl?: string
  }
  
  /*
   * IBikeEngineSpecs — engine and performance specifications.
   * All values stored as strings to preserve units and formatting.
   * Example: "373cc" not 373 — avoids unit ambiguity and unit conversion.
   */
  export interface IBikeEngineSpecs {
    displacement?: string    // "373 cc", "389 cc"
    engineType?: string      // "Single-cylinder, 4-stroke, DOHC"
    maxPower?: string        // "20.2 bhp @ 6100 rpm"
    maxTorque?: string       // "32 Nm @ 4000 rpm"
    fuelSystem?: string      // "Fuel Injection (EFI)"
    coolingType?: string     // "Air + Oil Cooled", "Liquid Cooled"
    transmission?: string    // "6-speed constant mesh"
    clutch?: string          // "Wet multi-plate"
    emission?: string        // "BS6 Phase 2"
    startingSystem?: string  // "Electric & Kick"
  }
  
  /*
   * IBikeDimensionSpecs — physical dimensions and capacities.
   * All values stored as strings with units included.
   */
  export interface IBikeDimensionSpecs {
    kerbWeight?: string      // "195 kg"
    fuelCapacity?: string    // "13 litres"
    seatHeight?: string      // "800 mm"
    groundClearance?: string // "170 mm"
    wheelbase?: string       // "1400 mm"
    overallLength?: string   // "2100 mm"
    overallWidth?: string    // "800 mm"
    overallHeight?: string   // "1120 mm"
  }
  
  /*
   * IBikeFeatures — boolean and string feature flags.
   * Boolean fields indicate presence/absence of a feature.
   * String fields indicate the type/variant of a feature.
   */
  export interface IBikeFeatures {
    abs?: boolean              // Anti-lock Braking System
    dualChannelAbs?: boolean   // Front + rear ABS (vs front-only)
    tractionControl?: boolean  // Traction control system
    ridingModes?: string[]     // ["Eco", "City", "Sport", "Rain"]
    bluetooth?: boolean        // Bluetooth connectivity
    usbCharging?: boolean      // USB-A or USB-C charging port
    quickshifter?: boolean     // Up/down quickshifter
    autoblipper?: boolean      // Auto-blipper on downshift
    cruiseControl?: boolean    // Cruise control system
    slipAssistClutch?: boolean // Slipper / assist clutch
    ledLights?: boolean        // Full LED lighting
    tft?: boolean              // TFT instrument cluster
    navigation?: boolean       // Built-in navigation
  }
  
  /*
   * IBikePricing — pricing information.
   * exShowroom: mandatory — the base price shown on all listings.
   * onRoad: optional — city-specific on-road price (varies by location).
   * Both stored in INR (Indian Rupees) as integers (no decimals).
   */
  export interface IBikePricing {
    exShowroom: number         // Base ex-showroom price in INR
    onRoad?: number            // On-road price in INR (optional, location-specific)
  }
  
  /*
   * IBikeSeoFields — SEO metadata stored per-bike.
   * Allows the admin to customise meta tags for each bike detail page.
   * Falls back to auto-generated values if not set (P-02 pattern).
   */
  export interface IBikeSeoFields {
    metaTitle?: string         // Custom <title> tag (max 60 chars)
    metaDescription?: string   // Custom <meta description> (max 160 chars)
    canonicalUrl?: string      // Explicit canonical URL if different from default
    ogImageUrl?: string        // Custom Open Graph image (defaults to heroImageUrl)
  }
  
  // ---------------------------------------------------------------------------
  // Primary Bike document interface
  // ---------------------------------------------------------------------------
  
  /*
   * IBike — the TypeScript interface for a Bike Mongoose document.
   * Extends Document to include Mongoose instance methods (.save(), etc.)
   * and virtuals (.id, ._id).
   *
   * This interface is used when working with documents returned from
   * Mongoose queries:
   *   const bike = await Bike.findOne({ slug: 'gt-650' })
   *   // bike is typed as IBike
   */
  export interface IBike extends Document {
    // ── Identity ────────────────────────────────────────────────────────
  
    /*
     * slug — URL-safe unique identifier for this bike.
     * Used as the [slug] route param in /bikes/[brandSlug]/[slug].
     * Format: lowercase kebab-case, alphanumeric and hyphens only.
     * Example: "gt-650", "duke-390", "himalayan-450"
     * Set by admin at creation time. Immutable after publishing.
     */
    slug: string
  
    /*
     * brandSlug — references the brand this bike belongs to.
     * Must match a slug in the Brand collection (DB-03).
     * Used for listing page queries and URL construction.
     * Example: "royal-enfield", "ktm", "yamaha"
     */
    brandSlug: string
  
    /*
     * name — full display name of the motorcycle model.
     * Shown in BikeCard (display-md) and BikeHero (display-xl).
     * Example: "GT 650", "Duke 390", "MT-15 V2"
     */
    name: string
  
    /*
     * tagline — one-line marketing tagline for the bike.
     * Shown in BikeCard (body-sm/ink-secondary) and meta description.
     * Example: "Modern Classic Roadster", "Ready to Race"
     */
    tagline: string
  
    /*
     * brandName — denormalised brand display name.
     * Stored on the Bike document to avoid a join when rendering
     * suggestion results in the search API (SR-07).
     * Example: "Royal Enfield", "KTM"
     */
    brandName: string
  
    /*
     * category — the MPD-approved category slug for this bike.
     * One of the 5 fixed categories from constants/categories.ts (S-08).
     */
    category: 'cruiser' | 'sport' | 'adventure' | 'naked' | 'scooter'
  
    /*
     * status — publish status of the bike listing.
     * draft:     only visible in the admin panel
     * published: visible on the public site
     */
    status: 'draft' | 'published'
  
    /*
     * publishedAt — timestamp when status was changed to 'published'.
     * Used for "Recently Added" sort on listing pages.
     * Null for drafts.
     */
    publishedAt: Date | null
  
    // ── Media ────────────────────────────────────────────────────────────
  
    /*
     * heroImageUrl — primary Cloudinary URL for the bike's hero image.
     * Used in BikeCard (4:3 thumbnail) and BikeHero (full-bleed).
     * Shows the default/first color variant.
     */
    heroImageUrl: string
  
    /*
     * blurDataUrl — base64 20px blur-up placeholder for heroImageUrl.
     * Generated at Cloudinary upload time. Used in Next.js Image
     * placeholder="blur" prop to prevent layout shift.
     */
    blurDataUrl?: string
  
    /*
     * gallery — ordered array of gallery images.
     * Rendered in the bike detail page image gallery (B-04).
     * Maximum 10 images per MPD spec.
     */
    gallery: IBikeGalleryImage[]
  
    /*
     * video360Url — optional Cloudinary URL for a 360-degree spin video.
     * Rendered with the 360° viewer component on the bike detail page (B-03).
     */
    video360Url?: string
  
    /*
     * colors — available color variants for this bike.
     * Minimum 1 (default color), maximum 8.
     * Each color has a name, hex swatch, and optional per-color image.
     */
    colors: IBikeColor[]
  
    // ── Pricing ──────────────────────────────────────────────────────────
  
    /*
     * pricing — ex-showroom and optional on-road pricing in INR.
     */
    pricing: IBikePricing
  
    // ── Specifications ────────────────────────────────────────────────────
  
    /*
     * specs — all technical specifications for the bike detail page.
     * Split into engine, dimensions, and features sub-documents.
     * All fields optional — allows partial spec entry in admin.
     */
    specs: {
      engine: IBikeEngineSpecs
      dimensions: IBikeDimensionSpecs
      features: IBikeFeatures
    }
  
    // ── SEO ──────────────────────────────────────────────────────────────
  
    /*
     * seo — per-bike SEO field overrides.
     * If not set, the detail page (P-02) generates meta tags from
     * name, tagline, and heroImageUrl automatically.
     */
    seo: IBikeSeoFields
  
    // ── Timestamps (auto-managed by Mongoose) ─────────────────────────────
  
    createdAt: Date
    updatedAt: Date
  }
  
  /*
   * IBikeInput — plain object type for creating or updating a Bike.
   * Used in API route handlers (DB-05/DB-06) where we receive
   * request body data and pass it to Bike.create() or bike.save().
   *
   * Omits Document-specific fields (_id, __v, createdAt, updatedAt)
   * that are managed by Mongoose.
   *
   * publishedAt and status have defaults and can be omitted on create.
   */
  export type IBikeInput = Omit<
  IBike,
  keyof Document | 'createdAt' | 'updatedAt' | 'publishedAt'
> & {
  publishedAt?: Date | null
  status?: 'draft' | 'published'
}
  
  // ---------------------------------------------------------------------------
  // Sub-document schemas
  // ---------------------------------------------------------------------------
  
  const BikeColorSchema = new Schema<IBikeColor>(
    {
      name: {
        type: String,
        required: [true, 'Color name is required'],
        trim: true,
        maxlength: [50, 'Color name must be 50 characters or fewer'],
      },
      hex: {
        type: String,
        required: [true, 'Color hex code is required'],
        trim: true,
        match: [
          /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
          'Color hex must be a valid CSS hex color (e.g. #1B3A8A)',
        ],
      },
      imageUrl: {
        type: String,
        trim: true,
      },
    },
    {
      /*
       * _id: false — sub-documents do not need their own _id.
       * Reduces document size and avoids unnecessary ObjectId generation
       * for embedded arrays that are never referenced individually.
       */
      _id: false,
    },
  )
  
  const BikeGalleryImageSchema = new Schema<IBikeGalleryImage>(
    {
      url: {
        type: String,
        required: [true, 'Gallery image URL is required'],
        trim: true,
      },
      alt: {
        type: String,
        required: [true, 'Gallery image alt text is required'],
        trim: true,
        maxlength: [200, 'Alt text must be 200 characters or fewer'],
      },
      blurDataUrl: {
        type: String,
        trim: true,
      },
    },
    { _id: false },
  )
  
  const BikeEngineSpecsSchema = new Schema<IBikeEngineSpecs>(
    {
      displacement: { type: String, trim: true },
      engineType: { type: String, trim: true },
      maxPower: { type: String, trim: true },
      maxTorque: { type: String, trim: true },
      fuelSystem: { type: String, trim: true },
      coolingType: { type: String, trim: true },
      transmission: { type: String, trim: true },
      clutch: { type: String, trim: true },
      emission: { type: String, trim: true },
      startingSystem: { type: String, trim: true },
    },
    { _id: false },
  )
  
  const BikeDimensionSpecsSchema = new Schema<IBikeDimensionSpecs>(
    {
      kerbWeight: { type: String, trim: true },
      fuelCapacity: { type: String, trim: true },
      seatHeight: { type: String, trim: true },
      groundClearance: { type: String, trim: true },
      wheelbase: { type: String, trim: true },
      overallLength: { type: String, trim: true },
      overallWidth: { type: String, trim: true },
      overallHeight: { type: String, trim: true },
    },
    { _id: false },
  )
  
  const BikeFeaturesSchema = new Schema<IBikeFeatures>(
    {
      abs: { type: Boolean },
      dualChannelAbs: { type: Boolean },
      tractionControl: { type: Boolean },
      ridingModes: [{ type: String, trim: true }],
      bluetooth: { type: Boolean },
      usbCharging: { type: Boolean },
      quickshifter: { type: Boolean },
      autoblipper: { type: Boolean },
      cruiseControl: { type: Boolean },
      slipAssistClutch: { type: Boolean },
      ledLights: { type: Boolean },
      tft: { type: Boolean },
      navigation: { type: Boolean },
    },
    { _id: false },
  )
  
  const BikePricingSchema = new Schema<IBikePricing>(
    {
      exShowroom: {
        type: Number,
        required: [true, 'Ex-showroom price is required'],
        min: [0, 'Price cannot be negative'],
      },
      onRoad: {
        type: Number,
        min: [0, 'On-road price cannot be negative'],
      },
    },
    { _id: false },
  )
  
  const BikeSeoSchema = new Schema<IBikeSeoFields>(
    {
      metaTitle: {
        type: String,
        trim: true,
        maxlength: [70, 'Meta title must be 70 characters or fewer'],
      },
      metaDescription: {
        type: String,
        trim: true,
        maxlength: [165, 'Meta description must be 165 characters or fewer'],
      },
      canonicalUrl: {
        type: String,
        trim: true,
      },
      ogImageUrl: {
        type: String,
        trim: true,
      },
    },
    { _id: false },
  )
  
  // ---------------------------------------------------------------------------
  // Primary Bike schema
  // ---------------------------------------------------------------------------
  
  const BikeSchema = new Schema<IBike>(
    {
      // ── Identity ────────────────────────────────────────────────────
  
      slug: {
        type: String,
        required: [true, 'Bike slug is required'],
        trim: true,
        lowercase: true,
        match: [
          /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
          'Slug must be lowercase alphanumeric with hyphens only (e.g. gt-650)',
        ],
      },
  
      brandSlug: {
        type: String,
        required: [true, 'Brand slug is required'],
        trim: true,
        lowercase: true,
      },
  
      name: {
        type: String,
        required: [true, 'Bike name is required'],
        trim: true,
        maxlength: [100, 'Bike name must be 100 characters or fewer'],
      },
  
      tagline: {
        type: String,
        required: [true, 'Bike tagline is required'],
        trim: true,
        maxlength: [150, 'Tagline must be 150 characters or fewer'],
      },
  
      brandName: {
        type: String,
        required: [true, 'Brand name is required'],
        trim: true,
        maxlength: [100, 'Brand name must be 100 characters or fewer'],
      },
  
      category: {
        type: String,
        required: [true, 'Category is required'],
        enum: {
          values: ['cruiser', 'sport', 'adventure', 'naked', 'scooter'],
          message:
            'Category must be one of: cruiser, sport, adventure, naked, scooter',
        },
      },
  
      status: {
        type: String,
        required: true,
        enum: {
          values: ['draft', 'published'],
          message: 'Status must be either draft or published',
        },
        default: 'draft',
      },
  
      publishedAt: {
        type: Date,
        default: null,
      },
  
      // ── Media ────────────────────────────────────────────────────────
  
      heroImageUrl: {
        type: String,
        required: [true, 'Hero image URL is required'],
        trim: true,
      },
  
      blurDataUrl: {
        type: String,
        trim: true,
      },
  
      gallery: {
        type: [BikeGalleryImageSchema],
        default: [],
        validate: [
          {
            validator: function (gallery: IBikeGalleryImage[]) {
              return gallery.length <= 10
            },
            message: 'Gallery cannot contain more than 10 images',
          },
        ],
      },
  
      video360Url: {
        type: String,
        trim: true,
      },
  
      colors: {
        type: [BikeColorSchema],
        required: true,
        validate: [
          {
            validator: function (colors: IBikeColor[]) {
              return colors.length >= 1
            },
            message: 'At least one color variant is required',
          },
          {
            validator: function (colors: IBikeColor[]) {
              return colors.length <= 8
            },
            message: 'A bike can have a maximum of 8 color variants',
          },
        ],
      },
  
      // ── Pricing ──────────────────────────────────────────────────────
  
      pricing: {
        type: BikePricingSchema,
        required: [true, 'Pricing information is required'],
      },
  
      // ── Specifications ────────────────────────────────────────────────
  
      specs: {
        engine: {
          type: BikeEngineSpecsSchema,
          default: () => ({}),
        },
        dimensions: {
          type: BikeDimensionSpecsSchema,
          default: () => ({}),
        },
        features: {
          type: BikeFeaturesSchema,
          default: () => ({}),
        },
      },
  
      // ── SEO ──────────────────────────────────────────────────────────
  
      seo: {
        type: BikeSeoSchema,
        default: () => ({}),
      },
    },
    {
      /*
       * timestamps: true — Mongoose automatically manages:
       *   createdAt: set on document creation
       *   updatedAt: updated on every save/update
       * These are typed on IBike as Date fields.
       */
      timestamps: true,
  
      /*
       * collection: 'bikes' — explicit collection name.
       * Prevents Mongoose from using the default pluralised name 'bikes'
       * (which happens to be correct here) but being explicit avoids
       * surprises if the model name changes.
       */
      collection: 'bikes',
  
      /*
       * toJSON: { virtuals: true } — include virtual fields (like 'id')
       * when converting documents to JSON for API responses.
       */
      toJSON: { virtuals: true },
      toObject: { virtuals: true },
    },
  )
  
  // ---------------------------------------------------------------------------
  // Indexes
  // ---------------------------------------------------------------------------
  
  /*
   * slug: unique — one document per URL slug across the entire collection.
   * Enforces at database level: no two bikes can share the same slug.
   * The slug is used as the URL param /bikes/[brandSlug]/[slug].
   */
  BikeSchema.index({ slug: 1 }, { unique: true })
  
  /*
   * brandSlug + status compound index — the primary query pattern for
   * brand listing pages (DB-08):
   *   Bike.find({ brandSlug: 'royal-enfield', status: 'published' })
   * The compound index covers both fields in a single index scan.
   */
  BikeSchema.index({ brandSlug: 1, status: 1 })
  
  /*
   * category + status compound index — category listing page queries:
   *   Bike.find({ category: 'cruiser', status: 'published' })
   */
  BikeSchema.index({ category: 1, status: 1 })
  
  /*
   * status standalone index — admin panel queries:
   *   Bike.find({ status: 'draft' }) — all drafts
   *   Bike.find({ status: 'published' }) — all published
   * Also covered by the compound indexes above but a standalone index
   * is faster for status-only queries on large collections.
   */
  BikeSchema.index({ status: 1 })
  
  /*
   * publishedAt descending — "Recently Added" sort on listing pages:
   *   Bike.find({ status: 'published' }).sort({ publishedAt: -1 })
   * Descending order (-1) is stored directly in the index so sort
   * operations are served from the index without an additional sort pass.
   */
  BikeSchema.index({ publishedAt: -1 })
  
  /*
   * brandSlug + category + status — price/filter queries:
   *   Bike.find({ brandSlug: 'ktm', category: 'naked', status: 'published' })
   * Supports the FilterBar (LP-03) when both brand and category are filtered.
   */
  BikeSchema.index({ brandSlug: 1, category: 1, status: 1 })
  
  /*
   * pricing.exShowroom — price range listing page queries:
   *   Bike.find({ 'pricing.exShowroom': { $gte: 200000, $lte: 500000 } })
   */
  BikeSchema.index({ 'pricing.exShowroom': 1 })
  
  // ---------------------------------------------------------------------------
  // Pre-save middleware
  // ---------------------------------------------------------------------------
  
  /*
   * Pre-save hook: automatically set publishedAt when status changes to
   * 'published'. Clears publishedAt if status reverts to 'draft'.
   *
   * This ensures publishedAt accurately reflects the actual publish time
   * regardless of how the status field is changed (API, admin, seed script).
   */
  BikeSchema.pre('save', function (next) {
    if (this.isModified('status')) {
      if (this.status === 'published' && this.publishedAt === null) {
        this.publishedAt = new Date()
      } else if (this.status === 'draft') {
        this.publishedAt = null
      }
    }
    next()
  })
  
  // ---------------------------------------------------------------------------
  // Model export — singleton pattern
  // ---------------------------------------------------------------------------
  
  /*
   * Singleton model registration.
   *
   * mongoose.models.Bike — returns the existing model if already registered.
   * mongoose.model<IBike>('Bike', BikeSchema) — registers a new model.
   *
   * The `as Model<IBike>` cast is required because mongoose.models returns
   * Model<unknown> — TypeScript cannot infer the document type from the
   * models registry. The cast is safe because we control the schema.
   *
   * NEVER use:
   *   const Bike = mongoose.model<IBike>('Bike', BikeSchema)
   * This throws "Cannot overwrite `Bike` model once compiled" on HMR.
   *
   * ALWAYS use:
   *   mongoose.models.Bike || mongoose.model<IBike>('Bike', BikeSchema)
   */
  const Bike =
    (mongoose.models['Bike'] as Model<IBike> | undefined) ??
    mongoose.model<IBike>('Bike', BikeSchema)
  
  export default Bike