'use client'

/*
 * BikeFormGallery — Gallery & Media section of the BikeForm.
 *
 * MPD Task A-08.6:
 *   "Gallery: Hero Image URL (required, HTTPS), Thumbnail / Blur Placeholder
 *   URL (optional), Gallery Images with URL + Alt Text (dynamic list, max 15,
 *   drag-and-drop reorder, add/remove, live preview), 360° Video URL (optional).
 *   HTTPS URL validation, duplicate URL prevention, blur validation,
 *   parent error merging."
 *
 * FIELDS:
 *
 *   Hero Image (required):
 *     heroImageUrl        — primary motorcycle photo (HTTPS, required)
 *     heroBlurDataUrl     — low-quality blur placeholder (HTTPS, optional)
 *                           Labeled "Thumbnail / Blur Placeholder" in the UI.
 *                           Auto-generated by the upload system (A-07.2) when
 *                           the image is uploaded via MediaUploader; can also
 *                           be entered manually here.
 *
 *   Gallery Images (dynamic list, max GALLERY_MAX_IMAGES = 15):
 *     gallery[i].secureUrl — HTTPS image URL (required per existing item)
 *     gallery[i].altText   — accessibility alt text (optional, max 200 chars)
 *     gallery[i].blurDataUrl, publicId — preserved from existing items, not edited here
 *
 *   360° Video (optional):
 *     video360Url          — Cloudinary video URL (HTTPS, optional)
 *
 * IMAGE PREVIEW:
 *   Every URL input shows a live thumbnail:
 *     Empty URL      → grey box with image icon (placeholder)
 *     Non-HTTPS URL  → red X indicator (not fetched for security)
 *     Valid HTTPS URL → <img> element; failure tracked per URL string
 *     Failed to load → grey box with broken indicator
 *
 *   Broken URLs are tracked by URL string (not index) so drag-to-reorder
 *   does not reset or misattribute the broken state.
 *   Regular <img> is used (not Next.js Image) because:
 *     1. Image dimensions are unknown at render time
 *     2. Admin-only context — LCP optimisation is not required here
 *     3. Cloudinary and arbitrary HTTPS URLs cannot always be configured
 *        in next.config.ts remotePatterns upfront
 *
 * DRAG-AND-DROP REORDER:
 *   HTML5 DnD events on each gallery item card.
 *   draggingIndexRef (ref) — source index; read in onDrop without stale closures.
 *   draggingIndex (state)  — drives 35% opacity on the card being dragged.
 *   dragOverIndex (state)  — shows the accent insertion bar on the target card.
 *
 *   onDragLeave uses e.currentTarget.contains(e.relatedTarget as Node) to
 *   prevent the drag-over indicator from flickering when the cursor moves
 *   between child elements inside the target card.
 *
 *   On drop: insertion-based splice algorithm (same as GalleryUploader A-07.4).
 *   On dragend: clears all drag state as a safety net (fires even if the
 *   drop occurred outside a valid target).
 *
 * VALIDATION:
 *   Per-field blur validation using validators from A-08.6 additions:
 *     heroImageUrl:     validateHeroGalleryUrl (required + HTTPS)
 *     heroBlurDataUrl:  validateHttpsUrl (optional + HTTPS if provided)
 *     video360Url:      validateHttpsUrl (optional + HTTPS if provided)
 *     gallery[i].url:   validateGalleryItemUrl (required per item + HTTPS + dedup)
 *     gallery[i].altText: validateAltText (optional + max 200 chars)
 *
 *   Local blur errors stored in localErrors / localGalleryErrors state.
 *   Parent errors (BikeFormGalleryErrors from BikeFormShell) merged before
 *   render — local errors take precedence (they reflect the latest input).
 *
 * WHY 'use client':
 *   useState (localErrors, localGalleryErrors, draggingIndex, dragOverIndex,
 *             brokenUrls)
 *   useRef   (draggingIndexRef)
 *   useCallback (change, blur, DnD handlers, add/remove)
 *   DragEvent handlers (onDragStart, onDragEnter, onDragOver,
 *                       onDragLeave, onDrop, onDragEnd)
 */

import {
  useCallback,
  useRef,
  useState,
  type DragEvent,
} from 'react'
import Icon from '@/components/ui/Icon'
import MediaUploader from '@/components/admin/MediaUploader'
import GalleryUploader from '@/components/admin/GalleryUploader'
import type {
  GalleryChangeItem,
  GalleryInitialItem,
} from '@/components/admin/GalleryUploader'
import {
  validateHeroGalleryUrl,
  validateHttpsUrl,
  validateAltText,
  validateGalleryItemUrl,
  FIELD_LIMITS,
} from '@/lib/bike-form-validation'
import type {
  BikeFormGalleryValues,
  BikeFormGalleryItem,
  BikeFormGalleryErrors,
} from '@/types/bike-form'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MAX_GALLERY_IMAGES = FIELD_LIMITS.GALLERY_MAX_IMAGES

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface BikeFormGalleryProps {
  /*
   * values — the current Gallery section state from BikeFormShell.
   * Contains heroImageUrl, heroBlurDataUrl, gallery[], video360Url.
   */
  values: BikeFormGalleryValues

  /*
   * errors — section-level errors from BikeFormShell's last full validation.
   * Merged with local blur errors; local errors take precedence.
   */
  errors?: BikeFormGalleryErrors

  /*
   * onChange — fires on every field mutation with the updated values.
   * BikeFormShell wires this to updateGallery().
   */
  onChange: (values: BikeFormGalleryValues) => void

  /*
   * disabled — all inputs and buttons are inert when true (form is submitting).
   */
  disabled?: boolean

  brandSlug: string
  slug: string
}

// ---------------------------------------------------------------------------
// FieldLabel — label + optional character counter
// Identical pattern to BikeFormBasic, BikeFormSpecifications, BikeFormPricing.
// ---------------------------------------------------------------------------

interface FieldLabelProps {
  htmlFor:   string
  label:     string
  required?: boolean
  current?:  number
  max?:      number
}

function FieldLabel({
  htmlFor,
  label,
  required = false,
  current,
  max,
}: FieldLabelProps) {
  return (
    <div
      style={{
        display:        'flex',
        alignItems:     'baseline',
        justifyContent: 'space-between',
        marginBottom:   '6px',
      }}
    >
      <label
        htmlFor={htmlFor}
        className="admin-label"
        style={{ margin: 0 }}
      >
        {label}
        {required && (
          <span
            aria-hidden="true"
            style={{ color: '#C8102E', marginLeft: '3px', fontWeight: 400 }}
          >
            *
          </span>
        )}
      </label>

      {max !== undefined && current !== undefined && (
        <span
          aria-live="polite"
          aria-label={`${current} of ${max} characters used`}
          style={{
            fontFamily: 'var(--font-mono)',
            fontSize:   '11px',
            color:
              current > max
                ? '#C8102E'
                : current > max * 0.85
                ? '#B45309'
                : 'var(--color-ink-tertiary)',
            transition: 'color 150ms cubic-bezier(0.4,0,0.2,1)',
          }}
        >
          {current} / {max}
        </span>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// FieldError — inline error message
// Identical pattern to all other BikeForm section components.
// ---------------------------------------------------------------------------

interface FieldErrorProps {
  id:      string
  message: string | undefined
}

function FieldError({ id, message }: FieldErrorProps) {
  if (!message) return null

  return (
    <p
      id={id}
      role="alert"
      style={{
        fontFamily: 'var(--font-body)',
        fontSize:   '12px',
        color:      '#C8102E',
        margin:     '5px 0 0',
        display:    'flex',
        alignItems: 'flex-start',
        gap:        '4px',
        lineHeight: 1.5,
      }}
    >
      <span aria-hidden="true" style={{ flexShrink: 0, marginTop: '1px' }}>
        <Icon name="warning" size={12} strokeWidth={1.75} />
      </span>
      {message}
    </p>
  )
}

// ---------------------------------------------------------------------------
// ImagePreview — live thumbnail shown beside each URL input
// ---------------------------------------------------------------------------

interface ImagePreviewProps {
  /*
   * url — the URL to attempt rendering.
   * Empty string → empty placeholder.
   * Non-HTTPS → invalid indicator (image not fetched for security).
   * Valid HTTPS + isBroken → broken indicator.
   * Valid HTTPS + !isBroken → <img> element.
   */
  url:      string
  alt:      string
  size:     number
  isBroken: boolean
  onError:  (url: string) => void
}

function ImagePreview({ url, alt, size, isBroken, onError }: ImagePreviewProps) {
  const trimmed  = url.trim()
  const hasUrl   = trimmed.length > 0
  const isHttps  = trimmed.startsWith('https://')
  const showImg  = hasUrl && isHttps && !isBroken

  const containerStyle: React.CSSProperties = {
    width:           size,
    height:          size,
    flexShrink:      0,
    borderRadius:    6,
    overflow:        'hidden',
    border:          '1px solid var(--color-border-hairline)',
    backgroundColor: 'var(--color-surface-sunken)',
    display:         'flex',
    alignItems:      'center',
    justifyContent:  'center',
    position:        'relative',
  }

  if (showImg) {
    return (
      <div style={containerStyle} aria-hidden="true">
        {/*
         * Regular <img> for admin preview — see component header for rationale.
         * eslint-disable is required; this is intentional for admin context.
         */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={trimmed}
          alt={alt || 'Image preview'}
          onError={() => onError(trimmed)}
          draggable={false}
          style={{
            width:      '100%',
            height:     '100%',
            objectFit:  'cover',
            display:    'block',
            /*
             * pointerEvents: none — prevents native image drag from
             * interfering with the card's onDragStart handler.
             */
            pointerEvents: 'none',
          }}
        />
      </div>
    )
  }

  /*
   * Placeholder state — empty box with a contextual icon.
   *
   * Empty URL     → image frame icon (muted, guides the admin to enter a URL)
   * Non-HTTPS URL → X icon (signals the URL is invalid / insecure)
   * Failed URL    → X icon (signals the URL could not be loaded)
   */
  return (
    <div style={containerStyle} aria-hidden="true">
      {hasUrl && (!isHttps || isBroken) ? (
        /*
         * Invalid or broken URL indicator.
         * Red X — matches the error colour used in FieldError.
         */
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          aria-hidden="true"
          style={{ color: '#C8102E', opacity: 0.7 }}
        >
          <line x1="18" y1="6" x2="6"  y2="18" />
          <line x1="6"  y1="6" x2="18" y2="18" />
        </svg>
      ) : (
        /*
         * Empty state — image frame with mountain/triangle icon.
         * Standard "image placeholder" affordance.
         */
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
          style={{ color: 'var(--color-ink-tertiary)', opacity: 0.45 }}
        >
          <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
          <circle cx="8.5" cy="8.5" r="1.5" />
          <polyline points="21 15 16 10 5 21" />
        </svg>
      )}
    </div>
  )
}

// ---------------------------------------------------------------------------
// BikeFormGallery
// ---------------------------------------------------------------------------

export default function BikeFormGallery({
  values,
  errors,
  onChange,
  disabled = false,
  brandSlug,
  slug,
}: BikeFormGalleryProps) {

  // ── Local error state ──────────────────────────────────────────────────

  /*
   * localErrors — scalar field errors set on blur.
   * Covers heroImageUrl, heroBlurDataUrl, video360Url.
   */
  const [localErrors, setLocalErrors] = useState<{
    heroImageUrl?:    string
    heroBlurDataUrl?: string
    video360Url?:     string
  }>({})

  /*
   * localGalleryErrors — per-item errors set on blur.
   * Sparse array: undefined at positions with no errors.
   * Indexed to align with values.gallery.
   */
  const [localGalleryErrors, setLocalGalleryErrors] = useState<
    Array<{ url?: string; altText?: string } | undefined>
  >([])

  // ── Drag state ─────────────────────────────────────────────────────────

  /*
   * draggingIndexRef — stores the source gallery index during drag.
   * Used inside onDrop to avoid stale closure over the draggingIndex state.
   */
  const draggingIndexRef = useRef<number | null>(null)

  /*
   * draggingIndex — drives visual opacity on the card being dragged.
   * State (not only ref) because it triggers a re-render of the card.
   */
  const [draggingIndex, setDraggingIndex] = useState<number | null>(null)

  /*
   * dragOverIndex — drives the insertion indicator on the target card.
   */
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null)

  // ── Broken image tracking ──────────────────────────────────────────────

  /*
   * brokenUrls — URL strings that failed to load as <img> elements.
   * Tracked by URL string (not index) so reordering does not misattribute.
   *
   * The ImagePreview component calls onError when an image fails.
   * That triggers handleImageError which adds the URL to this Set.
   */
  const [brokenUrls, setBrokenUrls] = useState<Set<string>>(new Set())

  const handleImageError = useCallback((url: string): void => {
    setBrokenUrls((prev) => new Set([...prev, url]))
  }, [])

  // ── Merged errors ──────────────────────────────────────────────────────

  /*
   * Merge parent errors with local blur errors.
   * Local errors (from most recent blur) override parent errors for the
   * same field. This ensures the admin sees the latest validation result
   * even after the parent runs a full section validation on tab switch.
   */
  const mergedHeroImageUrl    = localErrors.heroImageUrl    ?? errors?.heroImageUrl
  const mergedHeroBlurDataUrl = localErrors.heroBlurDataUrl ?? errors?.heroBlurDataUrl
  const mergedVideo360Url     = localErrors.video360Url     ?? errors?.video360Url

  /*
   * Per-gallery-item merged errors.
   * For each index: local error wins over parent error for the same key.
   */
  const mergedGalleryErrors = values.gallery.map((_, index) => ({
    url:     localGalleryErrors[index]?.url     ?? errors?.gallery?.[index]?.url,
    altText: localGalleryErrors[index]?.altText ?? errors?.gallery?.[index]?.altText,
  }))

  // ── Scalar field handlers ─────────────────────────────────────────────

  /*
   * handleHeroUrlChange — updates heroImageUrl, clears its broken state
   * if the URL changed (old URL was broken; new URL should be tried fresh).
   */
  const handleHeroUrlChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>): void => {
      const next = e.target.value
      setBrokenUrls((prev) => {
        const updated = new Set(prev)
        updated.delete(values.heroImageUrl.trim())
        return updated
      })
      onChange({ ...values, heroImageUrl: next })
    },
    [values, onChange],
  )

  const handleHeroBlurDataUrlChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>): void => {
      const next = e.target.value
      setBrokenUrls((prev) => {
        const updated = new Set(prev)
        updated.delete(values.heroBlurDataUrl.trim())
        return updated
      })
      onChange({ ...values, heroBlurDataUrl: next })
    },
    [values, onChange],
  )

  const handleVideo360UrlChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>): void => {
      const next = e.target.value
      setBrokenUrls((prev) => {
        const updated = new Set(prev)
        updated.delete(values.video360Url.trim())
        return updated
      })
      onChange({ ...values, video360Url: next })
    },
    [values, onChange],
  )

  // ── Scalar blur handlers ──────────────────────────────────────────────

  const handleHeroUrlBlur = useCallback((): void => {
    const err = validateHeroGalleryUrl(values.heroImageUrl)
    setLocalErrors((prev) => ({ ...prev, heroImageUrl: err ?? undefined }))
  }, [values.heroImageUrl])

  const handleHeroBlurDataUrlBlur = useCallback((): void => {
    const err = validateHttpsUrl(values.heroBlurDataUrl)
    setLocalErrors((prev) => ({ ...prev, heroBlurDataUrl: err ?? undefined }))
  }, [values.heroBlurDataUrl])

  const handleVideo360UrlBlur = useCallback((): void => {
    const err = validateHttpsUrl(values.video360Url)
    setLocalErrors((prev) => ({ ...prev, video360Url: err ?? undefined }))
  }, [values.video360Url])

  // ── Gallery item: add / remove ────────────────────────────────────────

  /*
   * handleAddGalleryItem — appends a blank item row.
   * Capped at MAX_GALLERY_IMAGES.
   */
  const handleAddGalleryItem = useCallback((): void => {
    if (values.gallery.length >= MAX_GALLERY_IMAGES || disabled) return

    const blank: BikeFormGalleryItem = {
      secureUrl: '',
      altText:   '',
    }

    onChange({ ...values, gallery: [...values.gallery, blank] })
  }, [values, onChange, disabled])

  /*
   * handleRemoveGalleryItem — removes the item at the given index.
   * Also removes the corresponding local error entry so the sparse
   * array stays aligned with the updated gallery.
   */
  const handleRemoveGalleryItem = useCallback(
    (index: number): void => {
      const removed    = values.gallery[index]
      const nextGallery = values.gallery.filter((_, i) => i !== index)

      /*
       * Remove the old URL from brokenUrls so it is re-evaluated
       * if the same URL appears again in a future item.
       */
      if (removed?.secureUrl) {
        setBrokenUrls((prev) => {
          const updated = new Set(prev)
          updated.delete(removed.secureUrl.trim())
          return updated
        })
      }

      onChange({ ...values, gallery: nextGallery })

      setLocalGalleryErrors((prev) => {
        const next = [...prev]
        next.splice(index, 1)
        return next
      })
    },
    [values, onChange],
  )

  // ── Gallery item: field change ────────────────────────────────────────

  /*
   * handleGalleryItemChange — updates a single field on a specific gallery item.
   * Spreads all other items unchanged. Preserves blurDataUrl and publicId.
   */
  const handleGalleryItemChange = useCallback(
    (
      index: number,
      field: 'secureUrl' | 'altText',
      value: string,
    ): void => {
      if (field === 'secureUrl') {
        const oldUrl = values.gallery[index]?.secureUrl.trim()
        if (oldUrl) {
          setBrokenUrls((prev) => {
            const updated = new Set(prev)
            updated.delete(oldUrl)
            return updated
          })
        }
      }

      const updated = values.gallery.map((item, i) =>
        i === index ? { ...item, [field]: value } : item,
      )

      onChange({ ...values, gallery: updated })
    },
    [values, onChange],
  )

  // ── Gallery item: blur validation ─────────────────────────────────────

  /*
   * handleGalleryItemBlur — validates a single field on a specific gallery
   * item and updates the localGalleryErrors sparse array at that index.
   */
  const handleGalleryItemBlur = useCallback(
    (index: number, field: 'secureUrl' | 'altText'): void => {
      const item = values.gallery[index]
      if (!item) return

      let err: string | null = null

      if (field === 'secureUrl') {
        const allUrls = values.gallery.map((g) => g.secureUrl)
        err = validateGalleryItemUrl(item.secureUrl, index, allUrls)
      } else {
        err = validateAltText(item.altText ?? '', index)
      }

      setLocalGalleryErrors((prev) => {
        const next = [...prev]
        next[index] = {
          ...(next[index] ?? {}),
          [field === 'secureUrl' ? 'url' : 'altText']: err ?? undefined,
        }
        return next
      })
    },
    [values.gallery],
  )

  // ── Drag-and-drop handlers ────────────────────────────────────────────

  const handleItemDragStart = useCallback(
    (e: DragEvent<HTMLDivElement>, index: number): void => {
      if (disabled) {
        e.preventDefault()
        return
      }

      draggingIndexRef.current = index
      setDraggingIndex(index)

      e.dataTransfer.effectAllowed = 'move'

      /*
       * setData is required for Firefox — it does not start a drag
       * unless dataTransfer contains at least one item.
       * The value is not read back (we use draggingIndexRef instead).
       */
      e.dataTransfer.setData('text/plain', String(index))
    },
    [disabled],
  )

  const handleItemDragEnter = useCallback(
    (e: DragEvent<HTMLDivElement>, index: number): void => {
      e.preventDefault()
      if (disabled) return

      if (
        draggingIndexRef.current !== null &&
        index !== draggingIndexRef.current
      ) {
        setDragOverIndex(index)
      }
    },
    [disabled],
  )

  const handleItemDragOver = useCallback(
    (e: DragEvent<HTMLDivElement>): void => {
      e.preventDefault()
      if (disabled) return
      e.dataTransfer.dropEffect = 'move'
    },
    [disabled],
  )

  const handleItemDragLeave = useCallback(
    (e: DragEvent<HTMLDivElement>): void => {
      /*
       * Only clear dragOverIndex when the cursor truly leaves the card,
       * not just when moving between child elements.
       * e.relatedTarget is the element the cursor moved to.
       */
      if (!e.currentTarget.contains(e.relatedTarget as Node)) {
        setDragOverIndex(null)
      }
    },
    [],
  )

  const handleItemDrop = useCallback(
    (e: DragEvent<HTMLDivElement>, targetIndex: number): void => {
      e.preventDefault()

      const sourceIndex = draggingIndexRef.current

      /*
       * Clear all drag state before mutating the gallery array.
       * This prevents a flash where the gallery has been reordered
       * but the drag indicators are still visible.
       */
      draggingIndexRef.current = null
      setDraggingIndex(null)
      setDragOverIndex(null)

      if (sourceIndex === null || sourceIndex === targetIndex) return

      /*
       * Insertion-based reorder algorithm (same pattern as GalleryUploader A-07.4):
       *   1. Remove the dragged item.
       *   2. Find the target position in the shorter array.
       *   3. Splice the dragged item in before the target.
       *
       * Also reorder localGalleryErrors in sync so error indicators
       * follow their respective items after reordering.
       */
      const nextGallery = [...values.gallery]
      const [moved] = nextGallery.splice(sourceIndex, 1)
      nextGallery.splice(targetIndex, 0, moved)

      onChange({ ...values, gallery: nextGallery })

      setLocalGalleryErrors((prev) => {
        const next = [...prev]
        const [movedErr] = next.splice(sourceIndex, 1)
        next.splice(targetIndex, 0, movedErr)
        return next
      })
    },
    [values, onChange],
  )

  /*
   * handleItemDragEnd — safety net: clears all drag state even when the
   * drop occurred outside a valid drop target (user released mouse elsewhere).
   * onDragEnd always fires after onDrop, so double-clear is harmless.
   */
  const handleItemDragEnd = useCallback((): void => {
    draggingIndexRef.current = null
    setDraggingIndex(null)
    setDragOverIndex(null)
  }, [])

  // ── Derived values ─────────────────────────────────────────────────────

  const canAddImage = values.gallery.length < MAX_GALLERY_IMAGES && !disabled

  // ── Render ─────────────────────────────────────────────────────────────

  return (
    <>
      <style>{`
        /*
         * Group label — uppercase muted heading.
         * Identical pattern to bfs-spec-group-label and bfp-group-label.
         */
        .bfg-group-label {
          font-family:    var(--font-body);
          font-size:      11px;
          font-weight:    600;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color:          var(--color-ink-tertiary);
          margin:         0 0 16px;
        }

        /*
         * Section divider — consistent with all other BikeForm sections.
         */
        .bfg-divider {
          height:           1px;
          background-color: var(--color-border-hairline);
          margin:           24px 0;
        }

        /*
         * Hero image row — preview thumbnail beside the URL input.
         */
        .bfg-hero-row {
          display:     flex;
          gap:         12px;
          align-items: flex-start;
          margin-bottom: 16px;
        }

        .bfg-hero-row .bfg-hero-inputs {
          flex: 1;
          min-width: 0;
        }

        /*
         * Gallery item card — drag handle, preview, inputs, remove button.
         * Transitions smoothly for drag-over state.
         */
        .bfg-item-card {
          display:          flex;
          gap:              10px;
          align-items:      flex-start;
          padding:          12px;
          background-color: var(--color-surface-raised);
          border:           2px solid var(--color-border-hairline);
          border-radius:    8px;
          margin-bottom:    8px;
          position:         relative;
          transition:
            border-color  150ms cubic-bezier(0.4,0,0.2,1),
            opacity       150ms cubic-bezier(0.4,0,0.2,1),
            box-shadow    150ms cubic-bezier(0.4,0,0.2,1);
        }

        /*
         * Dragging — the card being dragged fades to 35% to signal it is
         * "in flight". Same visual pattern used in GalleryUploader (A-07.4).
         */
        .bfg-item-card--dragging {
          opacity:  0.35;
          cursor:   grabbing;
        }

        /*
         * Drag-over target — accent border + insertion bar on the left edge.
         */
        .bfg-item-card--drag-over {
          border-color: #7A2E2E;
          box-shadow:   0 0 0 3px rgba(122,46,46,0.14);
        }

        /*
         * Drag insertion indicator — thin accent bar on the left edge of the
         * target card. Signals "the dragged card will be inserted before this one."
         */
        .bfg-insert-bar {
          position:         absolute;
          top:              0;
          left:             0;
          bottom:           0;
          width:            4px;
          background-color: #7A2E2E;
          border-radius:    2px 0 0 2px;
          pointer-events:   none;
        }

        /*
         * Drag handle — three-line icon on the left of the card.
         * Only shown and functional when disabled=false.
         */
        .bfg-drag-handle {
          display:          flex;
          align-items:      center;
          justify-content:  center;
          width:            24px;
          height:           24px;
          border-radius:    4px;
          color:            var(--color-ink-tertiary);
          cursor:           grab;
          flex-shrink:      0;
          margin-top:       4px;
          transition:       color 150ms cubic-bezier(0.4,0,0.2,1);
          user-select:      none;
        }

        .bfg-drag-handle:hover {
          color: var(--color-ink-secondary);
        }

        .bfg-drag-handle:active {
          cursor: grabbing;
        }

        /*
         * Card inputs area — fills the space between handle and remove button.
         */
        .bfg-item-inputs {
          flex:      1;
          min-width: 0;
          display:   flex;
          flex-direction: column;
          gap:       8px;
        }

        /*
         * Preview + URL in a flex row inside the card inputs area.
         */
        .bfg-item-url-row {
          display:     flex;
          gap:         10px;
          align-items: flex-start;
        }

        .bfg-item-url-row .bfg-item-url-input {
          flex:      1;
          min-width: 0;
        }

        /*
         * Remove button — matches the pattern from BikeFormPricing's
         * bfp-remove-btn (subtle by default, red on hover).
         */
        .bfg-remove-btn {
          display:          flex;
          align-items:      center;
          justify-content:  center;
          width:            30px;
          height:           30px;
          flex-shrink:      0;
          border-radius:    6px;
          background-color: var(--color-surface-sunken);
          border:           1px solid var(--color-border-hairline);
          color:            var(--color-ink-tertiary);
          cursor:           pointer;
          margin-top:       2px;
          transition:
            background-color 150ms cubic-bezier(0.4,0,0.2,1),
            color             150ms cubic-bezier(0.4,0,0.2,1),
            border-color      150ms cubic-bezier(0.4,0,0.2,1);
        }

        .bfg-remove-btn:hover:not(:disabled) {
          background-color: #FEE2E2;
          border-color:     #FECACA;
          color:            #C8102E;
        }

        .bfg-remove-btn:focus-visible {
          outline:    none;
          box-shadow: var(--shadow-focus);
        }

        .bfg-remove-btn:disabled {
          opacity: 0.4;
          cursor:  not-allowed;
        }

        /*
         * Add image button — secondary outlined style.
         * Matches bfp-add-btn from BikeFormPricing.
         */
        .bfg-add-btn {
          display:          inline-flex;
          align-items:      center;
          gap:              6px;
          height:           36px;
          padding:          0 14px;
          font-family:      var(--font-body);
          font-size:        13px;
          font-weight:      500;
          color:            var(--color-ink-secondary);
          background-color: var(--color-surface-raised);
          border:           1px solid var(--color-border-hairline);
          border-radius:    8px;
          cursor:           pointer;
          user-select:      none;
          transition:
            background-color 150ms cubic-bezier(0.4,0,0.2,1),
            color             150ms cubic-bezier(0.4,0,0.2,1),
            border-color      150ms cubic-bezier(0.4,0,0.2,1);
        }

        .bfg-add-btn:hover:not(:disabled) {
          background-color: var(--color-surface-sunken);
          border-color:     var(--color-ink-tertiary);
          color:            var(--color-ink-primary);
        }

        .bfg-add-btn:focus-visible {
          outline:    none;
          box-shadow: var(--shadow-focus);
        }

        .bfg-add-btn:disabled {
          opacity: 0.45;
          cursor:  not-allowed;
        }

        /*
         * Empty state — shown when gallery is empty.
         */
        .bfg-empty-state {
          padding:          16px;
          border:           1.5px dashed var(--color-border-hairline);
          border-radius:    8px;
          text-align:       center;
          background-color: var(--color-surface-sunken);
          margin-bottom:    10px;
        }

        /*
         * Drag hint row — shown below the gallery list when multiple items exist.
         */
        .bfg-drag-hint {
          display:     flex;
          align-items: center;
          gap:         5px;
          margin-top:  4px;
          font-family: var(--font-body);
          font-size:   11px;
          color:       var(--color-ink-tertiary);
        }

        /*
         * Count badge — shows "N / 15" above the gallery list.
         */
        .bfg-count-badge {
          display:     inline-flex;
          align-items: center;
          gap:         4px;
          margin-left: 8px;
          padding:     1px 7px;
          font-family: var(--font-mono);
          font-size:   10px;
          font-weight: 500;
          color:       var(--color-ink-secondary);
          background-color: var(--color-surface-sunken);
          border:      1px solid var(--color-border-hairline);
          border-radius: 999px;
          vertical-align: middle;
          text-transform: none;
          letter-spacing: 0;
        }

        /*
         * Sub-label inside gallery item cards.
         * Smaller than admin-label, identifies the URL and Alt Text inputs.
         */
        .bfg-sub-label {
          font-family: var(--font-body);
          font-size:   11px;
          font-weight: 500;
          color:       var(--color-ink-tertiary);
          display:     block;
          margin-bottom: 4px;
        }

        /*
         * Video section note — communicates that video is optional.
         */
        .bfg-video-hint {
          font-family: var(--font-body);
          font-size:   11px;
          color:       var(--color-ink-tertiary);
          margin:      5px 0 0;
          line-height: 1.5;
        }

        /*
         * Position number badge on gallery items.
         */
        .bfg-position-badge {
          position:         absolute;
          bottom:           8px;
          left:             8px;
          background-color: rgba(14,15,18,0.55);
          border-radius:    4px;
          padding:          1px 6px;
          font-family:      var(--font-mono);
          font-size:        10px;
          font-weight:      500;
          color:            rgba(255,255,255,0.9);
          pointer-events:   none;
          user-select:      none;
        }
      `}</style>

      <div>

        {/* ── Section 1: Hero Image ──────────────────────────────── */}
        <section aria-label="Hero image">
          <p className="bfg-group-label">Hero Image</p>

          {/* Hero Image URL — required */}
          <div className="bfg-hero-row">
            {/*
             * Live preview thumbnail beside the hero URL input.
             * size=80: generous enough to see the image composition
             * without consuming too much horizontal space.
             */}
            <ImagePreview
              url={values.heroImageUrl}
              alt="Hero image preview"
              size={80}
              isBroken={brokenUrls.has(values.heroImageUrl.trim())}
              onError={handleImageError}
            />

            <div className="bfg-hero-inputs">
              <FieldLabel
                htmlFor="bfg-heroImageUrl"
                label="Hero Image URL"
                required
              />

<MediaUploader
  intent="bike_hero"
  brandSlug={brandSlug}
  slug={slug}
  currentUrl={values.heroImageUrl}
  disabled={disabled}
  onUploadComplete={(result, blurDataUrl) => {
    onChange({
      ...values,
      heroImageUrl: result.secure_url,
      heroBlurDataUrl:
  blurDataUrl ?? values.heroBlurDataUrl,
    })
    setLocalErrors(prev => ({
      ...prev,
      heroImageUrl: undefined,
    }))
  }}
/>

              {!mergedHeroImageUrl && (
                <p
                  id="bfg-heroImageUrl-hint"
                  style={{
                    fontFamily: 'var(--font-body)',
                    fontSize:   '11px',
                    color:      'var(--color-ink-tertiary)',
                    margin:     '5px 0 0',
                  }}
                >
                  Primary motorcycle photograph. Minimum 1200 × 900px. Upload via drag-and-drop or browse.
                  Use the media edit page to upload and get the Cloudinary URL.
                </p>
              )}

              <FieldError
                id="bfg-heroImageUrl-error"
                message={mergedHeroImageUrl}
              />
            </div>
          </div>

          {/* Thumbnail / Blur Placeholder URL — optional */}
          <div className="bfg-hero-row">
            <ImagePreview
              url={values.heroBlurDataUrl}
              alt="Thumbnail placeholder preview"
              size={80}
              isBroken={brokenUrls.has(values.heroBlurDataUrl.trim())}
              onError={handleImageError}
            />

            <div className="bfg-hero-inputs">
              <FieldLabel
                htmlFor="bfg-heroBlurDataUrl"
                label="Thumbnail / Blur Placeholder URL"
              />

              <input
                id="bfg-heroBlurDataUrl"
                type="url"
                value={values.heroBlurDataUrl}
                onChange={handleHeroBlurDataUrlChange}
                onBlur={handleHeroBlurDataUrlBlur}
                disabled={disabled}
                placeholder="https://res.cloudinary.com/your-cloud/image/upload/w_20,h_20,e_blur:1000/..."
                className="admin-input"
                style={{
                  width:     '100%',
                  boxSizing: 'border-box',
                  ...(mergedHeroBlurDataUrl && { borderColor: '#C8102E' }),
                }}
                aria-describedby={[
                  'bfg-heroBlurDataUrl-hint',
                  mergedHeroBlurDataUrl ? 'bfg-heroBlurDataUrl-error' : '',
                ]
                  .filter(Boolean)
                  .join(' ') || undefined}
                aria-invalid={!!mergedHeroBlurDataUrl}
                autoComplete="off"
                spellCheck={false}
              />

              {!mergedHeroBlurDataUrl && (
                <p
                  id="bfg-heroBlurDataUrl-hint"
                  style={{
                    fontFamily: 'var(--font-body)',
                    fontSize:   '11px',
                    color:      'var(--color-ink-tertiary)',
                    margin:     '5px 0 0',
                    lineHeight: 1.5,
                  }}
                >
                  Optional. A tiny (20×20px) blurred version of the hero image used
                  as a placeholder while the full image loads.
                  Auto-generated when you upload via the Media edit page.
                </p>
              )}

              <FieldError
                id="bfg-heroBlurDataUrl-error"
                message={mergedHeroBlurDataUrl}
              />
            </div>
          </div>
        </section>

        <div className="bfg-divider" aria-hidden="true" />

        {/* ── Section 2: Gallery Images ──────────────────────────── */}
<section aria-label="Gallery images">
  <p className="bfg-group-label">
    Gallery Images
    <span
      className="bfg-count-badge"
      aria-label={`${values.gallery.length} of ${MAX_GALLERY_IMAGES} gallery images`}
    >
      {values.gallery.length} / {MAX_GALLERY_IMAGES}
    </span>
  </p>

  <GalleryUploader
    brandSlug={brandSlug}
    slug={slug}
    initialItems={values.gallery.map(
      (item): GalleryInitialItem => ({
        secureUrl: item.secureUrl,
        blurDataUrl: item.blurDataUrl,
      }),
    )}
    maxImages={MAX_GALLERY_IMAGES}
    onChange={(items: GalleryChangeItem[]) => {
      onChange({
        ...values,
        gallery: items.map((item, index) => ({
          secureUrl: item.secureUrl,
          blurDataUrl: item.blurDataUrl ?? '',
          publicId: item.publicId,
          altText: values.gallery[index]?.altText ?? '',
        })),
      })
    }}
    disabled={disabled}
  />
</section>

<div className="bfg-divider" aria-hidden="true" />
        {/* ── Section 3: 360° Video ──────────────────────────────── */}
        <section aria-label="360 degree spin video">
          <p className="bfg-group-label">360° Spin Video</p>

          <FieldLabel
            htmlFor="bfg-video360Url"
            label="360° Video URL"
          />

          <input
            id="bfg-video360Url"
            type="url"
            value={values.video360Url}
            onChange={handleVideo360UrlChange}
            onBlur={handleVideo360UrlBlur}
            disabled={disabled}
            placeholder="https://res.cloudinary.com/your-cloud/video/upload/..."
            className="admin-input"
            style={{
              width:     '100%',
              boxSizing: 'border-box',
              ...(mergedVideo360Url && { borderColor: '#C8102E' }),
            }}
            aria-describedby={[
              'bfg-video360Url-hint',
              mergedVideo360Url ? 'bfg-video360Url-error' : '',
            ]
              .filter(Boolean)
              .join(' ') || undefined}
            aria-invalid={!!mergedVideo360Url}
            autoComplete="off"
            spellCheck={false}
          />

          {!mergedVideo360Url && (
            <p
              id="bfg-video360Url-hint"
              className="bfg-video-hint"
            >
              Optional. Continuous 360° rotation video for the Bike360Viewer
              component. Upload via the Media edit page to get the Cloudinary URL.
              Accepted formats: MP4, WEBM, MOV.
            </p>
          )}

          <FieldError
            id="bfg-video360Url-error"
            message={mergedVideo360Url}
          />
        </section>
      </div>
    </>
  )
}